//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEETING_ORGANIZER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevular
    {
        public int ID { get; set; }
        public string ToplantiKonusu { get; set; }
        public string Tarih { get; set; }
        public string BaslangicSaati { get; set; }
        public string BitisSaati { get; set; }
        public string Katilimcilar { get; set; }
    }
}
